apiVersion: apps/v1
kind: Deployment
metadata:
  name: srs
spec:
  selector:
    matchLabels:
      app: srs
  template:
    metadata:
      labels:
        app: srs
    spec:
      containers:
      - name: srs
        image: registry.gitlab.com/infinitydon/registry/srslte:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true        
        command: ["/bin/sh", "-c"]
        args:
        - ip route add 10.240.230.0/24 via 10.240.233.75 && ip netns add ue1 && bash
        volumeMounts:
        - name: srs-enb-conf
          mountPath: /srsLTE/build/srsenb/src/enb.conf
        - name: srs-drb-conf
          mountPath: /srsLTE/build/srsenb/src/drb.conf
        - name: srs-rr-conf
          mountPath: /srsLTE/build/srsenb/src/rr.conf
        - name: srs-sib-conf
          mountPath: /srsLTE/build/srsenb/src/sib.conf
        - name: srs-ue-conf
          mountPath: /srsLTE/build/srsue/src/ue.conf
      volumes:
        - name: srs-enb-conf
          hostPath:
            path: /root/LB-vEPC-5GCore/ipvs-srsran-open5gs-configs/srsLTE-config/enb/enb.conf
            type: FileOrCreate
        - name: srs-drb-conf
          hostPath:
            path: /root/LB-vEPC-5GCore/ipvs-srsran-open5gs-configs/srsLTE-config/enb/drb.conf
            type: FileOrCreate
        - name: srs-rr-conf
          hostPath:
            path: /root/LB-vEPC-5GCore/ipvs-srsran-open5gs-configs/srsLTE-config/enb/rr.conf
            type: FileOrCreate
        - name: srs-sib-conf
          hostPath:
            path: /root/LB-vEPC-5GCore/ipvs-srsran-open5gs-configs/srsLTE-config/enb/sib.conf
            type: FileOrCreate
        - name: srs-ue-conf
          hostPath:
            path: /root/LB-vEPC-5GCore/ipvs-srsran-open5gs-configs/srsLTE-config/ue/ue.conf
            type: FileOrCreate



#docker run -it --privileged --name srs -v /root/LB-vEPC-5GCore/ipvs-srsran-open5gs-configs/srsLTE-config/enb/enb.conf:/srsLTE/build/srsenb/src/enb.conf -v /root/LB-vEPC-5GCore/ipvs-srsran-open5gs-configs/srsLTE-config/enb/drb.conf:/srsLTE/build/srsenb/src/drb.conf -v /root/LB-vEPC-5GCore/ipvs-srsran-open5gs-configs/srsLTE-config/enb/rr.conf:/srsLTE/build/srsenb/src/rr.conf -v /root/LB-vEPC-5GCore/ipvs-srsran-open5gs-configs/srsLTE-config/enb/sib.conf:/srsLTE/build/srsenb/src/sib.conf -v /root/LB-vEPC-5GCore/ipvs-srsran-open5gs-configs/srsLTE-config/ue/ue.conf:/srsLTE/build/srsue/src/ue.conf registry.gitlab.com/infinitydon/registry/srslte:latest bash