apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ausf-config
  labels:
    epc-mode: ausf
data:
  ausf.yaml: |
    logger:
        file: /var/log/open5gs/ausf.log

    ausf:
      sbi:
      - addr: 0.0.0.0
        advertise: {{ .Release.Name }}-ausf
    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf