apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nrf-config
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    logger:
        file: /var/log/open5gs/nrf.log

    nrf:
        sbi:
          addr: 0.0.0.0
