apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwu-pfcp
  namespace: open5gs
  labels:
    epc-mode: sgwu
spec:
  selector:
    epc-mode: sgwu
  ports:
  - name: pfcp
    port: 8805
    protocol: UDP
    targetPort: pfcp
    nodePort: null     
---
apiVersion: v1
kind: Service
metadata:
  name: open5gs-sgwu-gtpu
  namespace: open5gs
  labels:
    epc-mode: sgwu
spec:
  selector:
    epc-mode: sgwu
  ports:
  - name: gtpu
    port: 2152
    protocol: UDP
    targetPort: gtpu
    nodePort: null     
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-sgwu-deployment
  namespace: open5gs   
  labels:
    epc-mode: sgwu
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: sgwu
  template:
    metadata:
      labels:
        epc-mode: sgwu
    spec:   
      containers:
      - name: sgwu
        image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
        - open5gs-sgwud -c /open5gs/config-map/sgwu.yaml;
        ports:
          - name: pfcp
            containerPort: 8805
            protocol: UDP
          - name: gtpu
            containerPort: 2152
            protocol: UDP
        volumeMounts:
          - name: open5gs-sgwu-config
            mountPath: /open5gs/config-map/sgwu.yaml
            subPath: "sgwu.yaml"              
      volumes:
        - name: open5gs-sgwu-config
          configMap:
            name: open5gs-sgwu-config
