apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-sgwc-config
  namespace: open5gs
  labels:
    epc-mode: sgwc
data:
  sgwc.yaml: |
    logger:
        file: /var/log/open5gs/sgwc.log

    parameter:
        no_ipv6: true

    sgwc:
        gtpc:
           dev: eth0
           port: 2123
        pfcp:
           dev: eth0
           port: 8805

    sgwu:
      pfcp:
        - name: open5gs-sgwu-pfcp
          port: 8805
          apn: {{ .Values.apn }}
