apiVersion: v1
kind: ConfigMap
metadata:
  name: mme-addr-port
data:
  mme_addr_port: |
    10.240.233.199
    10.240.233.200

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipvs-sh-cmd
data:
  ipvs.sh: |

    #!/usr/bin/bash

    exec 1> /var/log/ipvsadm-log.txt 2>&1
    set -x

    IPVS=/usr/sbin/ipvsadm
    VIP=20.20.20.1 #Define VIP
    VPORT=36412 #Define the virtual port of LVS
    RPORT=36412 #Define the port of Realserver

    $IPVS -A --sctp-service $VIP:$VPORT -s rr

    del_realserver() { #Define the function to delete Realserver
      $IPVS -ln | grep -w $1
      if [ "$?" = 0 ]
      then
        echo "Host $i is in the ipvsadm table, proceeding to delete it"
        $IPVS -d --sctp-service $VIP:$VPORT -r $1:$RPORT
        echo "Proceeding to delete Host $1"
      else
      echo "Host $1 is already deleted, no further action needed"
      fi
    }

    add_realserver() {  #Define the function of adding Realserver
      $IPVS -ln | grep -w $1
      if [ "$?" = 0 ]
      then
        echo "Host $1 is already in the ipvsadm table, no further action needed"
      else
        echo "Host $i is not in the ipvsadm table, proceeding to add it"
        $IPVS -a --sctp-service $VIP:$VPORT -r $Host:$RPORT -i
        echo "Host $1 has been added"
      fi
    }
    file='mme_addr_port'
    while true; do
      while read line;do 

        Host=$line

        fping -c3 -t300 $Host 2>/dev/null 1>/dev/null

        if [ "$?" = 0 ]
        then
          echo "Host $Host is up, proceeding to check if it is in the ipvsadm table and add if it is not in the ipvsadm table"
          add_realserver $Host
        else
          echo "Host $Host is down, proceeding to check if it is in the ipvsadm"
          del_realserver $Host
        fi
        sleep 3
      done < $file
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mme-lb-deploy
  namespace: "default"
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: mme-lb-deploy
  template:
    metadata:
      labels:
        app: mme-lb-deploy
    spec:
      containers:
      - name: mme-lb
        image: ubuntu:focal
        command: ["sh -c"]
        args:
          - "apt-get update && apt-get install -y iptables ipvsadm iproute2 inetutils-ping fping tcpdump && \
            ip link set up tunl0 && \
            ip addr add 20.20.20.1 dev tunl0 && \
            echo 1 > /proc/sys/net/ipv4/ip_forward && \
            chmod +x /root/ipvs.sh && \
            bash /root/ipvs.sh"
        volumeMounts:
          - name: mme-addr-port
            mountPath: /root/mme_addr_port
          - name: ipvs-sh
            mountPath: /root/ipvs.sh
      volumes:
        - name: mme-addr-port
          configMap:
            name: mme-addr-port
        - name: ipvs-sh
          configMap:
            name: ipvs-sh-cmd
